### PR TITLE
Add Catalan translation in fusion-icon.desktop

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by XRevan86** [comment]
> Icona de Compiz Fusion

It's rather "Fusion Icona de Compiz".

**Comment by rbuj** [comment]
Compiz Fusion should not be translated. Because Compiz Fusion is the name of a software component, in fact Compiz Fusion = Compiz + Beryl.

**Comment by rbuj** [comment]
Compiz Fusion is the name of software component bundle, project name too, for that reason I translated "Compiz Fusion Icon" as "Icon of Compiz Fusion".

**Comment by XRevan86** [comment]
@rbuj, a name of the project that is long gone that is…

**Comment by rbuj** [comment]
I going to translate the po file, thanks ;-)

**Pull request closed without merging**
